#!/bin/sh
# ipgen is Copyright (C) 2012 Roy Hills, NTA Monitor Ltd.
#
# This file is part of ipgen.
#
# ipgen is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ipgen is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ipgen.  If not, see <http://www.gnu.org/licenses/>.
#
# check-output - Shell script to test ipgen output
#
# Author: Roy Hills
# Date: 28 May 2012
#
# This script checks that ipgen produces the correct output.
#

IPGENOUTPUT=/tmp/ipgen-output.$$.tmp
IPGENINPUT=/tmp/ipgen-input.$$.tmp
EXAMPLEOUTPUT=/tmp/example-output.$$.tmp

echo "Checking ipgen output for CIDR, net:mask, range and host..."
cat >$EXAMPLEOUTPUT <<_EOF_
10.0.0.1
10.0.0.2
10.0.0.3
10.0.0.4
10.0.0.5
10.0.0.6
10.1.0.1
10.1.0.2
10.1.0.3
10.1.0.4
10.1.0.5
10.1.0.6
10.2.0.1
10.2.0.2
10.2.0.3
10.2.0.4
10.2.0.5
10.2.0.6
10.3.0.1
_EOF_
./ipgen 10.0.0.0/29 10.1.0.0:255.255.255.248 10.2.0.1-10.2.0.6 10.3.0.1 > $IPGENOUTPUT 2>&1
if test $? -ne 0; then
   rm -f $IPGENOUTPUT
   rm -f $EXAMPLEOUTPUT
   echo "FAILED"
   exit 1
fi
cmp -s $IPGENOUTPUT $EXAMPLEOUTPUT
if test $? -ne 0; then
   rm -f $IPGENOUTPUT
   rm -f $EXAMPLEOUTPUT
   echo "FAILED"
   exit 1
fi
echo "ok"
rm -f $IPGENOUTPUT
rm -f $EXAMPLEOUTPUT
#
echo "Checking ipgen output with --network and --broadcast..."
cat >$EXAMPLEOUTPUT <<_EOF_
10.0.0.0
10.0.0.1
10.0.0.2
10.0.0.3
10.0.0.4
10.0.0.5
10.0.0.6
10.0.0.7
10.1.0.0
10.1.0.1
10.1.0.2
10.1.0.3
10.1.0.4
10.1.0.5
10.1.0.6
10.1.0.7
_EOF_
./ipgen -n -b 10.0.0.0/29 10.1.0.0:255.255.255.248 > $IPGENOUTPUT 2>&1
if test $? -ne 0; then
   rm -f $IPGENOUTPUT
   rm -f $EXAMPLEOUTPUT
   echo "FAILED"
   exit 1
fi
cmp -s $IPGENOUTPUT $EXAMPLEOUTPUT
if test $? -ne 0; then
   rm -f $IPGENOUTPUT
   rm -f $EXAMPLEOUTPUT
   echo "FAILED"
   exit 1
fi
echo "ok"
rm -f $IPGENOUTPUT
rm -f $EXAMPLEOUTPUT
#
echo "Checking ipgen reading from file..."
cat >$IPGENINPUT <<_EOF_
10.0.0.0/29
10.1.0.0:255.255.255.248
_EOF_
cat >$EXAMPLEOUTPUT <<_EOF_
10.0.0.1
10.0.0.2
10.0.0.3
10.0.0.4
10.0.0.5
10.0.0.6
10.1.0.1
10.1.0.2
10.1.0.3
10.1.0.4
10.1.0.5
10.1.0.6
_EOF_
./ipgen -f $IPGENINPUT > $IPGENOUTPUT 2>&1
if test $? -ne 0; then
   rm -f $IPGENOUTPUT
   rm -f $EXAMPLEOUTPUT
   echo "FAILED"
   exit 1
fi
cmp -s $IPGENOUTPUT $EXAMPLEOUTPUT
if test $? -ne 0; then
   rm -f $IPGENOUTPUT
   rm -f $EXAMPLEOUTPUT
   echo "FAILED"
   exit 1
fi
echo "ok"
rm -f $IPGENINPUT
rm -f $IPGENOUTPUT
rm -f $EXAMPLEOUTPUT
