'\" t
.\" Copyright (C) Roy Hills, NTA Monitor Ltd.
.\"
.\" Copying and distribution of this file, with or without modification,
.\" are permitted in any medium without royalty provided the copyright
.\" notice and this notice are preserved.
.\"
.\" $Id$
.TH IPGEN 1 "May 26, 2012"
.\" Please adjust this date whenever revising the man page.
.SH NAME
ipgen \- Output a list of host address from IP network specifications
.SH SYNOPSIS
.B ipgen
.RI [ options ] " " [ IP-Network ...]
.SH DESCRIPTION
.SH OPTIONS
.TP
.B --help or -h
Display this usage message and exit.
.SH FILES
.SH EXAMPLES
.SH AUTHOR
Roy Hills <Roy.Hills@nta-monitor.com>
.SH "SEE ALSO"
