name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]

    steps:
    - uses: actions/checkout@v3
    - name: autoreconf
      run: autoreconf --install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
#    - name: make distcheck
#      run: make distcheck
